 
language: cpp

jobs:
  include:
    - name: Ubuntu 16.04 build
      os: linux
      dist: xenial
      env:
        - QT5_BASE_DIR=/opt/qt515
        - PATH=/opt/qt515/bin/:$PATH
        - UPLOADTOOL_ISPRERELEASE=true


    - name: macOS build
      os: osx
      osx_image: xcode11.3
      env:
        - QT5_BASE_DIR=/usr/local/opt/qt
        - UPLOADTOOL_ISPRERELEASE=true
      before_install:
        # Delete all packages since updating them takes too much time
        - brew remove --force $(brew list) --ignore-dependencies
        - brew tap coslyk/mpv
        - brew update
        - brew install cmake qt openssl mpv-lite md5deep

    
    - name: Windows (VS2017 x64) build
      os: windows
      env:
        - PLATFORM=x64
        - QT5_BASE_DIR=C:/Qt/5.12.9/msvc2017_64
        - PATH=/c/Qt/5.12.9/msvc2017_64/bin:$PATH
        - UPLOADTOOL_ISPRERELEASE=true
      before_install:
        # Install libmpv, qt and innosetup
        - choco install -y zip innosetup 7zip
        - scripts/travis-install-mpv.bat
        - scripts/travis-install-qt.sh
        


# Install dependencies on Linux
addons:
  apt:
    sources:
      - sourceline: 'ppa:cos-lyk/libmpv-xenial'
      - sourceline: 'ppa:cos-lyk/qt-lite'
    packages:
      - desktop-file-utils
      - ffmpeg
      - libcurl4-openssl-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libmpv-dev
      - qt515base
      - qt515declarative
      - qt515quickcontrols2
      - qt515tools
      - qt515x11extras
    update: true


cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
    - /C/Qt/5.12.9

before_cache:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi


script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake -A x64 -DCMAKE_PREFIX_PATH=$QT5_BASE_DIR .; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$QT5_BASE_DIR -DCMAKE_INSTALL_PREFIX=/usr .; fi
  - cmake --build . --config Release


after_success:
  - scripts/deploy-${TRAVIS_OS_NAME}.sh
  - curl -Lo upload.sh https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh MoonPlayer*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
