 
language: cpp

jobs:
  include:
    - name: Ubuntu 14.04 build
      os: linux
      dist: trusty
      env:
        - QT5_BASE_DIR: /usr/local/Qt/5.12.6/gcc_64
        - PATH: /usr/local/Qt/5.12.6/gcc_64/bin/:$PATH

    - name: macOS build
      os: osx
      env:
        - QT5_BASE_DIR: /usr/local/opt/qt
    
    - name: Windows (VS2017 x64) build
      os: windows
      env:
        - PLATFORM: x64
        - QT5_BASE_DIR: C:/Qt/5.12.6/msvc2017_64
        - PATH: /c/Python37:/c/Python37/Scripts:$PATH


# Install dependencies for linux and macOS
addons:
  apt:
    sources:
      - sourceline: 'ppa:mc3man/testing6'
    packages:
      - build-essential
      - cmake
      - desktop-file-utils
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libxkbcommon-x11-0
      - libmpv-dev
    update: true

  homebrew:
    taps: coslyk/mpv
    packages:
      - cmake
      - pkg-config
      - qt
      - mpv-lite
    update: true


cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - travis-cache

before_cache:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then .travis/travis-cache-windows.sh save; fi
  
before_install:
  - chmod a+x .travis/pkg2appimage .travis/*.sh

install:
  # Install innosetup, zip, Qt and libmpv on Windows
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .travis/travis-cache-windows.sh restore; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .travis/travis-install-qt-windows.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then curl -Lo libmpv.zip https://github.com/coslyk/moonplayer/releases/download/2.9.2/libmpv_win_x64.zip; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then unzip -o libmpv.zip -d libmpv; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y zip innosetup; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install -y python --version 3.7.6; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then pip install pyinstaller; fi

  # install Qt 5.12 on Linux
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then .travis/travis-install-qt-linux.sh; fi


script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake -A x64 -DCMAKE_PREFIX_PATH=$QT5_BASE_DIR .; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$QT5_BASE_DIR .; fi
  - cmake --build . --config Release
  
before_deploy:
  - .travis/deploy-${TRAVIS_OS_NAME}.sh


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: D/oXrqI/M8RBR/GZU4io4rYo7PpLv5ixkX+HF9to8zxwbbdqySwFr11fQpNGrH0oISPziXqRWOVZpaKdyxCHh9OG5FSn1rCzBtUMiS6+LDGwX2l/rWcEr2TvBtKqQOML0pCCHZ4ZTfYDYvXpqib+hrSMeln2RfsdxS7iAc6JgoLwdArWo6+4r82VFwz4ON2BnorPg7o0p0QJO1WZVcte+JhmmqpgRyzg4Fal82MvCpEtmNM/X5he//OfQsijQ+jahKbHmZHIra6Hre+tyZpRUbQMVZJrg7S+POcge4e9pgm6Fxyy5BObeyjou523xhGitD66lwsw87Nmh3XUaFyGAfQ8lrxWr01JyiNmgBVzgWd+ZJIPUvkmlVtm+riE9BrP9TRq56nnjbWeA9oQJcQDBn8wMCo/ivEQt4lEJr1l7+fxqVvJqz7StMhBPV1pbSI9QKTgIBtDr/RuaWIgRQ9hYyD/+P8e7934rkB/bSYHEmzH7NKUmMRPbjzeO+WedKKaXOuJXLyHQcVY70KS+DWxmAgLUK7TEhgdGYYKlLuM8lFAHE0RbrYsPbsE6qalP8AeEevxdAlCpMThOzmnP3a9Hkni2PLn0E3YAHeN6GcJrfWrigdldLbCpwc54mJwOKuVWq1W1OFLsC3eXP1SHnh7IaGvJpSoDaogI4W+ldr96nw=
  file:
    - out/*.AppImage
    - MoonPlayer_*.zip
    - MoonPlayer_*.exe
  file_glob: true
  on:
    repo: coslyk/moonplayer
    tags: true
