 
language: cpp

jobs:
  include:
    - name: Ubuntu 14.04 build
      os: linux
      dist: trusty
      env:
        - QT5_BASE_DIR: $HOME/Qt/5.15.1/gcc_64
        - PATH: $HOME/Qt/5.15.1/gcc_64/bin/:$PATH


    - name: macOS build
      os: osx
      env:
        - QT5_BASE_DIR: /usr/local/opt/qt
      before_install:
        # Delete all packages since updating them takes too much time
        - brew remove --force $(brew list) --ignore-dependencies
        - brew tap coslyk/mpv
        - brew update
        - brew install cmake qt openssl mpv-lite md5deep

    
    - name: Windows (VS2017 x64) build
      os: windows
      env:
        - PLATFORM: x64
        - QT5_BASE_DIR: C:/Qt/5.12.8/msvc2017_64
        - PATH: /c/Qt/5.12.8/msvc2017_64/bin:$PATH
      before_install:
        # Install libmpv, innosetup and pyinstaller
        - scripts/travis-cache-windows.sh restore
        - curl -Lo libmpv.zip https://github.com/coslyk/moonplayer/releases/download/2.9.2/libmpv_win_x64.zip
        - unzip -o libmpv.zip -d libmpv
        - choco install -y zip innosetup 7zip
        


# Install dependencies on Linux
addons:
  apt:
    sources:
      - sourceline: 'ppa:cos-lyk/libmpv-trusty'
    packages:
      - build-essential
      - cmake
      - desktop-file-utils
      - ffmpeg
      - libcurl4-openssl-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libxkbcommon-x11-0
      - libmpv-dev
      - p7zip-full
    update: true


cache:
  directories:
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew
    - $HOME/Qt/5.15.1/gcc_64
    - travis-cache

before_cache:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cleanup; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then scripts/travis-cache-windows.sh save; fi


install:
  # install Qt 5.12 on Windows and Linux
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then scripts/travis-install-qt.sh; fi


script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake -A x64 -DCMAKE_PREFIX_PATH=$QT5_BASE_DIR .; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=$QT5_BASE_DIR -DCMAKE_INSTALL_PREFIX=/usr .; fi
  - cmake --build . --config Release


after_success:
  - scripts/deploy-${TRAVIS_OS_NAME}.sh
  - bash scripts/upload.sh MoonPlayer*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
