app: moonplayer

ingredients:
  dist: bionic
  sources:
    - deb http://archive.ubuntu.com/ubuntu/ bionic main restricted universe multiverse
  packages:
    - ffmpeg
    - libmpv1
    - libqt5widgets5
    - libqt5network5
    - libqt5x11extras5
    - qml-module-qtquick2
    - qml-module-qtquick-controls2
    - qml-module-qtquick-dialogs
    - qml-module-qtquick-layouts
    - qml-module-qtquick-window2
    - qml-module-qt-labs-settings
  exclude:
    - libegl1
    - libpython2.7
    - python-talloc
  script:
    - echo "${TRAVIS_TAG}-bionic" > VERSION

script:
  - cp -rf ../../usr/local/* usr/
  - cp usr/share/icons/com.github.coslyk.MoonPlayer.png .
  - cp usr/share/applications/com.github.coslyk.MoonPlayer.desktop .
  - mv ./usr/lib/x86_64-linux-gnu/samba/*.so* ./usr/lib/x86_64-linux-gnu/
  - sed -i -e 's|PYTHONHOME|PYTHOMHOME|g' AppRun
  - sed -i -e 's|PYTHONPATH|PYTHOMPATH|g' AppRun

